Resources:
  Logs:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "logs"
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: logName
          AttributeType: S
        - AttributeName: sequence
          AttributeType: S
        - AttributeName: stream
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: Range
      LocalSecondaryIndexes:
        - IndexName: log
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: logName
              KeyType: RANGE
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes:
              - sequence
        - IndexName: logStream
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: sequence
              KeyType: RANGE
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes:
              - id
              - payload
              - type
              - createdAt
      GlobalSecondaryIndexes:
        - IndexName: streamById
          KeySchema:
            - AttributeName: stream
              KeyType: HASH
            - AttributeName: sequence
              KeyType: RANGE
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes:
              - id
              - payload
              - type
              - createdAt
      SSESpecification:
        SSEType: 'AES256'
      StreamSpecification:
        StreamEnabled: true
        StreamViewType: 'NEW_IMAGE'
      Tags:
        -
          Key: "dynamodb-table"
          Value: "logs"
